### ISSUE TITLE
One-character abbreviations

### ISSUE THREAD

**Issue by hlabrand** [DavidKinder/Inform6#141]
" Abbreviate "e"; " gives an error ("not worth abbreviating") that in the compiler is triggered by a length check. This makes sense because "e" is one unit and an abbreviation is two.

" Abbreviate "é"; " does not give an error; presumably because it is compiled into "@'e" ?

" Abbreviate "{"; " gives an error. This error is wrong: { is not in the A2 alphabet and is thus 4 units, which an abbreviation would help with.

" Abbreviate "@@123"; " does not give an error, again because only the length is checked. But the abbreviation just doesnt work, whether you use a { or a @@123 in your strings.

I honestly dont mind if the last case doesnt work if I am able to abbreviate { (yes, I really need to, for an obscure reason). I disabled the check and recompiled the compiler.

Could I suggest downgrading this error to a warning? Or removing the check altogether? Or the compiler could compute the weight of the abbreviation, including weird cases like @@123, but that might be more/too costly.

**Comment by erkyrath** [comment]
Downgrading to a warning makes sense. 

I think we can get correct measurement if we move the error (warning) to make_abbreviation(), and check if `quality <= 0`.

**Comment by erkyrath** [comment]
Fixed by https://github.com/DavidKinder/Inform6/pull/142 . 

The warning now appears if the abbreviation is two Z-chars or less. This means that, for example,

    Abbreviate "an";

...will generate a warning.

**Comment by hlabrand** [comment]
Actually this doesn't quite solve it: some logic has to change to now correctly abbreviate 1-char abbreviations. (The compiler never actually does the abbreviating.)

I think it's in try_abbreviations_from in text.c : 

```
    for (j=from, p=(uchar *)abbreviations_at+from*MAX_ABBREV_LENGTH;
         (j<no_abbreviations)&&(c==p[0]); j++, p+=MAX_ABBREV_LENGTH)
    {   if (text[i+1]==p[1])

```

This looks at the second character, and if it's also a match, it does the for loop, replacing with 1s, etc. It's probably there to avoid creating a for loop if the second character is not even the right one; but this means that if the abbreviation is 1-char long, it'll never be triggered.

Not sure what's the best way to fix it so not have performance loss... Maybe  "  if (text[i+1]==p[1] || p[1] == 0) " ?
Thanks!

**Comment by hlabrand** [comment]
I forgot that try_abbreviations_from had been "deprecated" in z-machine. (Funny, cause I did that last month.)

The code that needs to be changed is on line 483; the simplest seems to be starting abbr_length to 1 and the for at 1 as well:
```
for (k=from, q=(uchar *)abbreviations_at+from*MAX_ABBREV_LENGTH;
                    (k<no_abbreviations)&&(c==q[0]); k++, q+=MAX_ABBREV_LENGTH)
                {   
                    /* Let's compare; we also keep track of the length of the abbreviation. */
                       abbr_length = 1;
                        for (l=1; q[l]!=0; l++)
                        {    if (text_in[j+l]!=q[l]) {goto NotMatched;} else {abbr_length++;}
                        }
(etc)
```

Does that seem like an OK fix?

**Comment by erkyrath** [comment]
I tried that; see commit https://github.com/DavidKinder/Inform6/pull/142/commits/f368b3cbf0ec298e466c3643e041d175bbd7302b .

(It looks like a big change, but it's mostly re-indentation, because it's no longer in an `if` block. I also removed the `abbr_length` variable because it was always equal to `l` anyhow.)

I think this is equivalent to what you suggested. Compiled games give the correct output, and abbreviations of length >=3 are used correctly. However, the `-f` switch shows that short abbreviations are still not being used.

**Comment by hlabrand** [comment]
Not sure what you mean by "short abbreviations are still not being used", because it works well for me :) I have a 4-unit 1-char one ("{", appearing 487 times and saving 648 bytes) and several 5-unit 2-char abbreviations and they all are used and shrink my game file. As far as I'm concerned, this looks fixed?
(Thanks for noticing that abbr_length could be removed!)

**Comment by erkyrath** [comment]
I mean that one- and two-unit abbreviations, which do not in fact save space, are ignored by the abbreviation code. You can define them now but they never get used.

I don't really care about this. I think it's a natural outcome of the abbreviation logic -- at least, I don't see a special case anywhere for short abbrevs. I have no desire to complicate that code to allow for abbreviations which don't improve file size. But it's worth noting in case anybody asks.
